default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: db
  database: app_development

test:
  <<: *default
  database: app_test

production:
  url: <%= ENV["DATABASE_URL"] %>
