services:
  - type: web
    name: manchester-is-red-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile.prod
    rootDir: .
    plan: free
    healthCheckPath: /
    startCommand: |
      mkdir -p tmp/pids && \
      rm -f tmp/pids/server.pid && \
      bundle exec rails db:migrate && \
      bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: manchester-is-red-db  # PostgreSQL用にデータベース名を合わせる
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        sync: false

  - type: web
    name: manchester-is-red-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile.prod
    rootDir: ./ 
    plan: free
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://manchester-is-red-backend.onrender.com

databases:
  - name: manchester-is-red-db  # PostgreSQLのデータベース名
    databaseName: manchester_is_red
    user: manchester_is_red
    plan: free
    ipAllowList: []
    engine: postgres  # MySQLからPostgreSQLに変更
    version: "13"  # PostgreSQLのバージョン（Renderに合わせて変更）
