FROM ruby:3.2.2

# 必要なパッケージのインストール
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs

# アプリケーションディレクトリの作成
RUN mkdir /app
WORKDIR /app

# Gemfileのコピーとインストール
COPY backend/Gemfile /app/Gemfile
COPY backend/Gemfile.lock /app/Gemfile.lock
RUN bundle install

# アプリケーションのコピー
COPY backend /app

# 環境設定
ENV RAILS_ENV=production
ENV RAILS_SERVE_STATIC_FILES=true

# ポートの公開
EXPOSE 3000

# 起動コマンド
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
