source "https://rubygems.org"

gem "puma", ">= 5.0"
gem "rails", "~> 8.0.2"
gem "tzinfo-data", platforms: %i[windows jruby]

# Use the database-backed adapters for Rails.cache, Active Job, and Action Cable
gem "solid_cable"
gem "solid_cache"
gem "solid_queue"

gem "bootsnap", require: false

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "dotenv-rails"
gem "httparty"
gem "rack-cors"
gem "thruster", require: false

gem 'nokogiri'
gem 'aws-sdk-s3'
gem 'rss'

group :development do
  gem "pry"
  gem "pry-rails"
  gem "rubocop", require: false
  gem "rubocop-rails", require: false
end

group :development, :test do
  gem "brakeman", require: false
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "rubocop-rails-omakase", require: false
  gem "mysql2", "~> 0.5.2"
end

group :production do
end
